name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Build
      run: dotnet build src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Teams/Microsoft.PowerToys.Run.Plugin.Teams.csproj --configuration Release

    - name: Test
      run: dotnet test src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Teams.UnitTests/Microsoft.PowerToys.Run.Plugin.Teams.UnitTests.csproj --configuration Release

    - name: Zip Release
      run: |
        Compress-Archive -Path src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Teams/bin/x64/Release/net8.0-windows/win-x64/* -DestinationPath PowerToys.Run.Plugin.Teams.zip

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: PowerToys.Run.Plugin.Teams.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 